# Generated by Django 3.2.16 on 2025-01-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_auto_20250103_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='toppings',
            field=models.ManyToManyField(to='ice_cream.Topping', verbose_name='Топпинги'),
        ),
        migrations.AlterField(
            model_name='wrapper',
            name='title',
            field=models.CharField(help_text='Уникальное название до 256 символов', max_length=256, verbose_name='Название'),
        ),
    ]
